#!/bin/sh
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket username and password in the script
USERNAME = "YOURBITBUCKETUSERNAME"
PASSWORD = "YOURBITBUCKETPASSWORD"
git init
echo "...git init"
git add -A .
echo "...git add -A"
git commit -m "Initial commit"
echo "...creating new remote repo on bitbucket"
echo "...with name ${PWD##*/}"
curl --user $USERNAME:$PASSWORD https://api.bitbucket.org/1.0/repositories/ --data name=${PWD##*/} --data is_private='true'
echo "...adding new repo remote URL git@bitbucket.org:$USERNAME/${PWD##*/}.git"
git remote add origin git@bitbucket.org:$USERNAME/${PWD##*/}.git
echo "...git push -u origin --all"
git push -u origin --all
git push -u origin --tags